services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiknet
  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"
