name: Update TypeScript shared cache

on:
  push:
    branches:
      - main

jobs:
  update-cache:
    strategy:
      fail-fast: false
    name: Update TypeScript shared cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
          
      - name: Restore TypeScript cache
        uses: actions/cache/restore@v4
        with:
          path: .tsbuildinfo
          key: shared-${{ hashFiles('tsconfig.json') }} # This will never hit, but it is required.
          restore-keys: shared-${{ hashFiles('tsconfig.json') }}

      - name: Typecheck
        run: bun run typecheck

      - name: Save shared cache for ${{ matrix.apps }}
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .tsbuildinfo
          key: shared-${{ hashFiles('tsconfig.json') }}-${{ github.run_id }}
